In [1]:
# import numpy as np
# create arrays
# np.array()
# np.arange()
# np.ones()
# np.zeros()
# np.eye()
# np.linspace()

# access items
# a[row, col], a[row][row]

# Facny indexing
# a[a==5], a[a<5]

# array shape
# a.shape , a=a.reshape()

# Operators:
# + - * / ** %
# > < >= <= == !=
# & | ~


# create matrix
# np.matrix()
# m.I

In [2]:
# Some functions
# np.mean() returns the average
# np.sum()  returns the sum
# np.std
# np.median
# np.var()
# np.max()
# np.min()
# np.argmax()
# np.argmin()
# np.argsort()
# np.argwhere()
# np.quantile

In [3]:
a=np.arange(20).reshape((4,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [8]:
np.mean(a, axis=1)

array([ 2.,  7., 12., 17.])

In [11]:
np.sum(a, axis=1)

array([10, 35, 60, 85])

In [13]:
np.max(a, axis=0)

array([15, 16, 17, 18, 19])

In [19]:
b=np.array([10,7,8,15,4,3])
b

array([10,  7,  8, 15,  4,  3])

In [20]:
np.argmax(b)

3

In [21]:
np.argmin(b)

5

In [23]:
np.sort(b)

array([ 3,  4,  7,  8, 10, 15])

In [22]:
np.argsort(b)

array([5, 4, 1, 2, 0, 3])

In [25]:
b

array([10,  7,  8, 15,  4,  3])

In [29]:
np.argwhere(b==15)[0,0]

3

In [30]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [31]:
np.argwhere(a%2==0)

array([[0, 0],
       [0, 2],
       [0, 4],
       [1, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [2, 4],
       [3, 1],
       [3, 3]])

In [36]:
c=np.array([10,  15,  10, 15,  4,  15])

In [42]:
np.unique(c, return_counts=True)

(array([ 4, 10, 15]), array([1, 2, 3]))

In [40]:
np.unique(c, return_counts=True)[0]

array([ 4, 10, 15])

In [41]:
np.unique(c, return_counts=True)[1]

array([1, 2, 3])

In [47]:
np.quantile(c, q=0.75)

15.0

In [134]:
np.arange(np.datetime64('2000-01-01'), np.datetime64('2001-01-01'), np.timedelta64(1,'W'))

array(['2000-01-01', '2000-01-08', '2000-01-15', '2000-01-22',
       '2000-01-29', '2000-02-05', '2000-02-12', '2000-02-19',
       '2000-02-26', '2000-03-04', '2000-03-11', '2000-03-18',
       '2000-03-25', '2000-04-01', '2000-04-08', '2000-04-15',
       '2000-04-22', '2000-04-29', '2000-05-06', '2000-05-13',
       '2000-05-20', '2000-05-27', '2000-06-03', '2000-06-10',
       '2000-06-17', '2000-06-24', '2000-07-01', '2000-07-08',
       '2000-07-15', '2000-07-22', '2000-07-29', '2000-08-05',
       '2000-08-12', '2000-08-19', '2000-08-26', '2000-09-02',
       '2000-09-09', '2000-09-16', '2000-09-23', '2000-09-30',
       '2000-10-07', '2000-10-14', '2000-10-21', '2000-10-28',
       '2000-11-04', '2000-11-11', '2000-11-18', '2000-11-25',
       '2000-12-02', '2000-12-09', '2000-12-16', '2000-12-23',
       '2000-12-30'], dtype='datetime64[D]')

In [136]:
np.arange(np.datetime64('2000-01'), np.datetime64('2001-01'), np.timedelta64(2,'M'))

array(['2000-01', '2000-03', '2000-05', '2000-07', '2000-09', '2000-11'],
      dtype='datetime64[M]')

In [139]:
np.arange(np.datetime64('2000-01'), np.datetime64('2020-01'), np.timedelta64(2,'Y'))

array(['2000-01', '2002-01', '2004-01', '2006-01', '2008-01', '2010-01',
       '2012-01', '2014-01', '2016-01', '2018-01'], dtype='datetime64[M]')

In [144]:
np.arange(np.datetime64('2000-01-01'), np.datetime64('2000-02-01'), np.timedelta64(2,'m'))

array(['2000-01-01T00:00', '2000-01-01T00:02', '2000-01-01T00:04', ...,
       '2000-01-31T23:54', '2000-01-31T23:56', '2000-01-31T23:58'],
      dtype='datetime64[m]')

In [145]:
'YYYY-MM-DDTHH:MM:SS'

'YYYY-MM-DDTHH:MM:SS'

In [147]:
from datetime import datetime

In [152]:
d='01/01/2000'.split('/')[0]
m='01/01/2000'.split('/')[1]
y='01/01/2000'.split('/')[2]
y+'-'+m+'-'+d

'2000-01-01'

**Exercise 01**

`answers.txt` contains students answers of exam questions (each line contains student_id, then answers made by that student)
- Write code to read the data from the file, compare students answers to answers key (1 point for each correct answer), then find: 

    - Means score.
    - Id of student of the highest score.
    - Id of student of the lowest score.

`answerkey = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D"`

**Hint:** *Try to use numpy arrays*

In [77]:
answerkey = "B,A,D,D,C,B,D,A,C,C,D,B,A,B,A,C,B,D,A,C,A,A,B,D,D"
answerkey= np.array(answerkey.split(','))
answerkey

array(['B', 'A', 'D', 'D', 'C', 'B', 'D', 'A', 'C', 'C', 'D', 'B', 'A',
       'B', 'A', 'C', 'B', 'D', 'A', 'C', 'A', 'A', 'B', 'D', 'D'],
      dtype='<U1')

In [83]:
import numpy as np
d=np.loadtxt('answers.txt',delimiter=',', dtype=str)
print('The average score',np.mean(d[:,1:]==answerkey))

The average score 0.784


In [106]:
index_of_highest_score_student=np.argmax(np.sum(d[:,1:]==answerkey, axis=1))

In [124]:
print('Id of student of the highest score:',d[index_of_highest_score_student,0])

Id of student of the highest score: N00000016


In [125]:
print('Id of student of the lowest score:',d[np.argmin(np.sum(d[:,1:]==answerkey, axis=1)),0])

Id of student of the lowest score: N00000001


## Generate random numbers

In [171]:
np.random.seed(1)

In [172]:
np.random.randn(10)   # standard normal distribution

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038])

In [154]:
np.random.rand(10)  # uniform distribution

array([0.6404199 , 0.55285155, 0.88913639, 0.4906787 , 0.51923288,
       0.40719683, 0.76977734, 0.49186552, 0.52081864, 0.00614324])

In [156]:
np.random.randint(10,100,5)

array([52, 66, 76, 82, 86])

In [157]:
np.random.random_sample(10)

array([0.43932549, 0.90390859, 0.68423131, 0.27969959, 0.31821183,
       0.29611042, 0.23320562, 0.57746718, 0.91994893, 0.19715965])

In [166]:
data=['hasan','ali','alma','sarah','mike']
sample=np.random.choice(data,2,replace=False,p=[0.6, 0.1, 0.1,0.1,0.1])

In [167]:
sample

array(['hasan', 'alma'], dtype='<U5')

## Using stats

In [186]:
a=np.arange(20).reshape((5,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [190]:
a=a.reshape((1,-1))[0]

In [194]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [201]:
from scipy import stats
stats.describe(a)

DescribeResult(nobs=20, minmax=(0, 19), mean=9.5, variance=35.0, skewness=0.0, kurtosis=-1.206015037593985)

In [202]:
stats.describe(a).nobs

20

In [205]:
stats.describe(a)[2]

9.5

In [208]:
stats.describe(np.ones(10))

DescribeResult(nobs=10, minmax=(1.0, 1.0), mean=1.0, variance=0.0, skewness=0.0, kurtosis=-3.0)

In [212]:
data=['hasan', 'ali', 'alma', 'sarah', 'mike','hasan']

In [213]:
stats.itemfreq(data)

<ipython-input-213-2169ce7933ac>:1: DeprecationWarning: `itemfreq` is deprecated!
`itemfreq` is deprecated and will be removed in a future version. Use instead `np.unique(..., return_counts=True)`
  stats.itemfreq(data)


array([['ali', '1'],
       ['alma', '1'],
       ['hasan', '2'],
       ['mike', '1'],
       ['sarah', '1']], dtype='<U21')

In [214]:
np.unique(data, return_counts=True)

(array(['ali', 'alma', 'hasan', 'mike', 'sarah'], dtype='<U5'),
 array([1, 1, 2, 1, 1]))

In [215]:
freq={}
for v in data:
    if v not in freq:
        freq[v]=1
    else:
        freq[v]+=1
freq

{'hasan': 2, 'ali': 1, 'alma': 1, 'sarah': 1, 'mike': 1}

In [227]:
# Create a distribution

In [224]:
mynorm=stats.norm(10,9)

In [225]:
mynorm.rvs(10)

array([ 0.09442741, 20.30251339, 18.11431649, 14.52244905, 18.10770354,
        3.84644927,  8.89398797,  1.57807509,  7.58900728, 14.7731992 ])

In [226]:
mynorm.pdf(10)

0.04432692004460363

In [223]:
mynorm.cdf(10)

0.5

In [228]:
hdist=stats.norm(170, 10)

In [231]:
hdist.rvs(1000000)

array([166.15682902, 181.11189626, 161.68349322, ..., 160.10521411,
       162.68294894, 174.97990354])

In [234]:
hdist.cdf(180)

0.8413447460685429

In [235]:
hdist.pdf(160)

0.024197072451914336